### ISSUE TITLE
Check boxes cannot be removed

### ISSUE THREAD

**Issue by zebulasampedro** [ResearchComputing/oide-slurm-assist#5]
Check box fields in the Sbatch Builder cannot be removed.

**Comment by kansuke231** [comment]
Technically, checkboxes can be removed by "unchecking" them. It should be fixed in the future, however, so that those checkboxes also have some sort of add-on buttons beside them to make the UI consistent with other form inputs.

**Comment by kansuke231** [comment]
Checkboxes now have the same delete button (same UI) as the other inputs fields.
